datasets_args_list:
  - transform_type: raw (no transforms)
    transform_list:
      - - TransformSignal: identity
        
  - transform_type: raw (no transforms)
    transform_list:
                    

models_args_list:
  - model_type: ShallowFBCSPNet
    batch_size: 64
    seed: null
    n_classes: 6
    lr: 0.00625
    weight_decay: 0
    n_epochs: 100
    n_cross_val: 3
    train_split: True
  - model_type: RandomForest
    n_cross_val: 3

sample_size_list:
  - 0.01
  - 0.1
  - 0.25
  - 0.5
  - 1

saving_params: 
  file_name: model_v_2
  folder: /storage/store/work/sfreybur/result_folder/

