infos:
  folder_path: "/storage/store/data/camcan/camcan47/cc700/meg/pipeline/release004/data/aamod_meg_get_fif_00001/"
  list_indiv: 
    - 'CC110033'
    - 'CC110037'
    - 'CC110045'
  maxfilter_calibration_file_path: "sss_cal.dat"
  empty_room_path: "/storage/store/data/camcan/camcan47/cc700/meg/pipeline/release004/emptyroom/"
  event_id: 
    - Auditory 300Hz: 6 
    - Auditory 600Hz: 7
    - Auditory 1200Hz: 8 
    - Visual Checkerboard: 9
epochs:
  tmin: -0.2 
  tmax: 0.5
  factor_new: 0.001
  init_block_size: 1000
  trial_start_offset_seconds: -0.5
braindecode:
  window_size_samples: 50
  window_stride_samples: 50
  drop_last_window: False
  
